# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "smartdict-core"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Potapov Sergey"]
  s.date = "2012-07-17"
  s.description = "CLI dictionary created to help you to learn foreign languages."
  s.email = "blake131313@gmail.com"
  s.executables = ["smartdict", "smartdict-populator"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "./lib/smartdict-core.rb",
    "./lib/smartdict.rb",
    "./lib/smartdict/commands.rb",
    "./lib/smartdict/commands/abstract_command.rb",
    "./lib/smartdict/commands/has_format_list.rb",
    "./lib/smartdict/commands/help_command.rb",
    "./lib/smartdict/commands/list_command.rb",
    "./lib/smartdict/commands/translate_command.rb",
    "./lib/smartdict/commands/version_command.rb",
    "./lib/smartdict/core.rb",
    "./lib/smartdict/core/command_manager.rb",
    "./lib/smartdict/core/driver_manager.rb",
    "./lib/smartdict/core/format_manager.rb",
    "./lib/smartdict/core/has_logger.rb",
    "./lib/smartdict/core/is_manager.rb",
    "./lib/smartdict/core/logger.rb",
    "./lib/smartdict/core/plugin_manager.rb",
    "./lib/smartdict/drivers.rb",
    "./lib/smartdict/drivers/abstract_driver.rb",
    "./lib/smartdict/drivers/google_translate_driver.rb",
    "./lib/smartdict/drivers/lingvo_yandex_driver.rb",
    "./lib/smartdict/errors.rb",
    "./lib/smartdict/formats.rb",
    "./lib/smartdict/formats/abstract_format.rb",
    "./lib/smartdict/formats/fb2_format.rb",
    "./lib/smartdict/formats/text_color_format.rb",
    "./lib/smartdict/formats/text_format.rb",
    "./lib/smartdict/info.rb",
    "./lib/smartdict/log.rb",
    "./lib/smartdict/models.rb",
    "./lib/smartdict/models/driver.rb",
    "./lib/smartdict/models/language.rb",
    "./lib/smartdict/models/translated_word.rb",
    "./lib/smartdict/models/translation.rb",
    "./lib/smartdict/models/translation_query.rb",
    "./lib/smartdict/models/word.rb",
    "./lib/smartdict/models/word_class.rb",
    "./lib/smartdict/plugin.rb",
    "./lib/smartdict/plugin/initializer_context.rb",
    "./lib/smartdict/storage.rb",
    "./lib/smartdict/storage/seeder.rb",
    "./lib/smartdict/storage/seeds/drivers.csv",
    "./lib/smartdict/storage/seeds/languages.csv",
    "./lib/smartdict/storage/seeds/word_classes.csv",
    "./lib/smartdict/translation.rb",
    "./lib/smartdict/translator.rb",
    "./lib/smartdict/translator/base.rb",
    "./lib/smartdict/translator/driver_configuration.rb",
    "./lib/smartdict/translator/language_detector.rb",
    "./lib/smartdict/version.rb",
    "GPL-LICENSE.txt",
    "VERSION",
    "bin/smartdict",
    "config/default_config.yml"
  ]
  s.homepage = "http://github.com/smartdict/smartdict-core"
  s.licenses = ["GNU GPL v2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "CLI dictionary"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, [">= 0"])
      s.add_runtime_dependency(%q<dm-validations>, [">= 0"])
      s.add_runtime_dependency(%q<dm-enum>, [">= 0"])
      s.add_runtime_dependency(%q<dm-migrations>, [">= 0"])
      s.add_runtime_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_runtime_dependency(%q<configatron>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<builder>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<libnotify>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<rb-readline>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<dm-sweatshop>, [">= 0"])
      s.add_development_dependency(%q<dm-rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<simplecov-vim>, [">= 0"])
    else
      s.add_dependency(%q<dm-core>, [">= 0"])
      s.add_dependency(%q<dm-validations>, [">= 0"])
      s.add_dependency(%q<dm-enum>, [">= 0"])
      s.add_dependency(%q<dm-migrations>, [">= 0"])
      s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
      s.add_dependency(%q<configatron>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<builder>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<libnotify>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<rb-readline>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.1.2"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<dm-sweatshop>, [">= 0"])
      s.add_dependency(%q<dm-rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<simplecov-vim>, [">= 0"])
    end
  else
    s.add_dependency(%q<dm-core>, [">= 0"])
    s.add_dependency(%q<dm-validations>, [">= 0"])
    s.add_dependency(%q<dm-enum>, [">= 0"])
    s.add_dependency(%q<dm-migrations>, [">= 0"])
    s.add_dependency(%q<dm-sqlite-adapter>, [">= 0"])
    s.add_dependency(%q<configatron>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<builder>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<libnotify>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<rb-readline>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.1.2"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<dm-sweatshop>, [">= 0"])
    s.add_dependency(%q<dm-rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<simplecov-vim>, [">= 0"])
  end
end

