plugins:

store:
  adapter: sqlite

default:
  from_lang: en
  to_lang: ru
  format: text_color
  langs:
    - en
    - ru
    - de
    - es
    - fr

drivers:
  default: google_translate
  en-ru: lingvo_yandex
