module Smartdict::Seeder
  extend self

  def seed!
    seed_languages
    seed_word_classes
    seed_drivers
  end


  private

  def seed_languages
    seeds = {
      "ab" => "Abkhazian",
      "aa" => "Afar",
      "af" => "Afrikaans",
      "ak" => "Akan",
      "sq" => "Albanian",
      "am" => "Amharic",
      "ar" => "Arabic",
      "an" => "Aragonese",
      "hy" => "Armenian",
      "as" => "Assamese",
      "av" => "Avaric",
      "ae" => "Avestan",
      "ay" => "Aymara",
      "az" => "Azerbaijani",
      "bm" => "Bambara",
      "ba" => "Bashkir",
      "eu" => "Basque",
      "be" => "Belarusian",
      "bn" => "Bengali",
      "bh" => "Bihari languages",
      "bi" => "Bislama",
      "bs" => "Bosnian",
      "br" => "Breton",
      "bg" => "Bulgarian",
      "my" => "Burmese",
      "ca" => "Catalan",
      "km" => "Central Khmer",
      "ch" => "Chamorro",
      "ce" => "Chechen",
      "zh" => "Chinese",
      "za" => "Chuang",
      "cu" => "Church",
      "cv" => "Chuvash",
      "kw" => "Cornish",
      "co" => "Corsican",
      "cr" => "Cree",
      "hr" => "Croatian",
      "cs" => "Czech",
      "da" => "Danish",
      "nl" => "Dutch",
      "dz" => "Dzongkha",
      "en" => "English",
      "eo" => "Esperanto",
      "et" => "Estonian",
      "ee" => "Ewe",
      "fo" => "Faroese",
      "fj" => "Fijian",
      "fi" => "Finnish",
      "fr" => "French",
      "ff" => "Fulah",
      "gd" => "Gaelic",
      "gl" => "Galician",
      "lg" => "Ganda",
      "ka" => "Georgian",
      "de" => "German",
      "el" => "Greek, Modern",
      "kl" => "Greenlandic",
      "gn" => "Guarani",
      "gu" => "Gujarati",
      "ht" => "Haitian",
      "ha" => "Hausa",
      "he" => "Hebrew",
      "hz" => "Herero",
      "hi" => "Hindi",
      "ho" => "Hiri Motu",
      "hu" => "Hungarian",
      "is" => "Icelandic",
      "io" => "Ido",
      "ig" => "Igbo",
      "id" => "Indonesian",
      "ia" => "Interlingua",
      "ie" => "Interlingue",
      "iu" => "Inuktitut",
      "ik" => "Inupiaq",
      "ga" => "Irish",
      "it" => "Italian",
      "ja" => "Japanese",
      "jv" => "Javanese",
      "kn" => "Kannada",
      "kr" => "Kanuri",
      "ks" => "Kashmiri",
      "kk" => "Kazakh",
      "ki" => "Kikuyu",
      "rw" => "Kinyarwanda",
      "ky" => "Kirghiz",
      "kv" => "Komi",
      "kg" => "Kongo",
      "ko" => "Korean",
      "kj" => "Kuanyama",
      "ku" => "Kurdish",
      "lo" => "Lao",
      "la" => "Latin",
      "lv" => "Latvian",
      "li" => "Limburgish",
      "ln" => "Lingala",
      "lt" => "Lithuanian",
      "lu" => "Luba-Katanga",
      "lb" => "Luxembourgish",
      "mk" => "Macedonian",
      "mg" => "Malagasy",
      "ms" => "Malay",
      "ml" => "Malayalam",
      "dv" => "Maldivian",
      "mt" => "Maltese",
      "gv" => "Manx",
      "mi" => "Maori",
      "mr" => "Marathi",
      "mh" => "Marshallese",
      "mn" => "Mongolian",
      "na" => "Nauru",
      "nv" => "Navaho",
      "nv" => "Navajo",
      "nd" => "Ndebele, North",
      "nr" => "Ndebele, South",
      "ng" => "Ndonga",
      "ne" => "Nepali",
      "nd" => "North Ndebele",
      "se" => "Northern Sami",
      "no" => "Norwegian",
      "nn" => "Norwegian Nynorsk",
      "ii" => "Nuosu",
      "ny" => "Nyanja",
      "oc" => "Occitan (post 1500)",
      "oj" => "Ojibwa",
      "or" => "Oriya",
      "om" => "Oromo",
      "os" => "Ossetian",
      "os" => "Ossetic",
      "pi" => "Pali",
      "pa" => "Panjabi",
      "ps" => "Pashto",
      "fa" => "Persian",
      "pl" => "Polish",
      "pt" => "Portuguese",
      "pa" => "Punjabi",
      "ps" => "Pushto",
      "qu" => "Quechua",
      "ro" => "Romanian",
      "rm" => "Romansh",
      "rn" => "Rundi",
      "ru" => "Russian",
      "sm" => "Samoan",
      "sg" => "Sango",
      "sa" => "Sanskrit",
      "sc" => "Sardinian",
      "sr" => "Serbian",
      "sn" => "Shona",
      "sd" => "Sindhi",
      "si" => "Sinhala",
      "sk" => "Slovak",
      "sl" => "Slovenian",
      "so" => "Somali",
      "st" => "Sotho, Southern",
      "es" => "Spanish",
      "su" => "Sundanese",
      "sw" => "Swahili",
      "ss" => "Swati",
      "sv" => "Swedish",
      "tl" => "Tagalog",
      "ty" => "Tahitian",
      "tg" => "Tajik",
      "ta" => "Tamil",
      "tt" => "Tatar",
      "te" => "Telugu",
      "th" => "Thai",
      "bo" => "Tibetan",
      "ti" => "Tigrinya",
      "to" => "Tonga (Tonga Islands)",
      "ts" => "Tsonga",
      "tn" => "Tswana",
      "tr" => "Turkish",
      "tk" => "Turkmen",
      "tw" => "Twi",
      "ug" => "Uighur",
      "uk" => "Ukrainian",
      "ur" => "Urdu",
      "uz" => "Uzbek",
      "ve" => "Venda",
      "vi" => "Vietnamese",
      "wa" => "Walloon",
      "cy" => "Welsh",
      "fy" => "Western Frisian",
      "wo" => "Wolof",
      "xh" => "Xhosa",
      "yi" => "Yiddish",
      "yo" => "Yoruba",
      "zu" => "Zulu"
    }

    seeds.each do |code, name|
      Smartdict::Models::Language.create!(:code => code, :name => name)
    end
  end

  def seed_word_classes
    names = %w(noun adjective verb adverb preposition numeral interjection abbreviation undefined)
    names.each do |name|
      Smartdict::Models::WordClass.create!(:name => name)
    end
  end

  def seed_drivers
    names = %w(google_translate)
    names.each do |name|
      Smartdict::Models::Driver.create!(:name => name)
    end
  end
end
